[package]
name = 'closure'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'closure'

[dependencies]
libR-sys = "=0.7.0"
closure-core = { git = "https://github.com/lhdjung/closure-core" }
extendr-api = '*'
rayon = "1.10.0"

[profile.release]
opt-level = 3
lto = true
